apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - composition.yaml
patches:
  - path: templates/user.patch.yaml
    target: { kind: Composition, name: example-inline }
  - path: templates/access-key.patch.yaml
    target: { kind: Composition, name: example-inline }